---
title: "Bayesian Quantile Tobit regression in Stan"
author: "Miao Cai"
date: "12/23/2018"
output:
  html_document:
    theme: yeti
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
  pdf_document:
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval =FALSE)
```



$$TE = \mathbf{X^{\prime}\beta} + \epsilon \\
\epsilon \sim N(0, \sigma^2)$$

```{r tobitstan}
tobitstan = '
data {
  int<lower=0>  N0;        
  int<lower=0>  N1;        
  vector<lower=0,upper=1>[N0] Y0;  
  vector<lower=0,upper=1>[N1] Y1;  
  
  vector[N0] bed0;
  vector[N0] occ0;
  vector[N0] alos0;
  vector[N0] dnr0;
  vector[N0] bnr0;
  vector[N0] oir0;
  vector[N0] pop0;
  vector[N0] urban0;
  vector[N0] HHI_beds0;
  vector[N0] gdp0;

  vector[N1] bed1;
  vector[N1] occ1;
  vector[N1] alos1;
  vector[N1] dnr1;
  vector[N1] bnr1;
  vector[N1] oir1;
  vector[N1] pop1;
  vector[N1] urban1;
  vector[N1] HHI_beds1;
  vector[N1] gdp1;
}
parameters{
  real b0;
  real b1;
  real b2;
  real b3;
  real b4;
  real b5;
  real b6;
  real b7;
  real b8;
  real b9;
  real b10;
  real<lower=0> sigma;
}
model{
  Y0 ~ normal( b0 + b1*bed0 + b2*occ0 + b3*alos0 + b4*dnr0 + b5*bnr0 + b6*oir0 + b7*pop0 + b8*urban0 + b9*HHI_beds0 + b10*gdp0, sigma);
  
  target += normal_lccdf( Y1 | b1*bed1 + b2*occ1 + b3*alos1 + b4*dnr1 + b5*bnr1 + b6*oir1 + b7*pop1 + b8*urban1 + b9*HHI_beds1 + b10*gdp1, sigma );
  
  
  //PRIORS
  b0 ~ normal(0, 10);
  b1 ~ normal(0, 10);
  b2 ~ normal(0, 10);
  b3 ~ normal(0, 10);
  b4 ~ normal(0, 10);
  b5 ~ normal(0, 10);
  b6 ~ normal(0, 10);
  b7 ~ normal(0, 10);
  b8 ~ normal(0, 10);
  b9 ~ normal(0, 10);
  b10 ~ normal(0, 10);
  sigma ~ gamma(1, 1);
}
'
```


```{r tobitstan}
library(rstan)
options(mc.cores = parallel::detectCores())

dat = haven::read_dta("data/dat.dta")
datC  = dat[dat$TE == 1,]
datUN = dat[dat$TE != 1,]

scale1 = function(x) return((x - mean(x))/sd(x))

tdat1 = list(
  N0 = nrow(datUN),
  Y0 = datUN$TE,
  bed0 = scale1(datUN$bed),
  occ0 = scale1(datUN$occ),
  alos0 = scale1(datUN$alos),
  dnr0 = scale1(datUN$dnr), 
  bnr0 = scale1(datUN$bnr),
  oir0 = scale1(datUN$oir),
  pop0 = scale1(datUN$pop),
  urban0 = scale1(datUN$urban),
  HHI_beds0 = scale1(datUN$HHI_beds),
  gdp0 = scale1(datUN$gdp),
  N1 = nrow(datC),
  Y1 = datC$TE,
  bed1 = scale1(datC$bed),
  occ1 = scale1(datC$occ),
  alos1 = scale1(datC$alos),
  dnr1 = scale1(datC$dnr), 
  bnr1 = scale1(datC$bnr),
  oir1 = scale1(datC$oir),
  pop1 = scale1(datC$pop),
  urban1 = scale1(datC$urban),
  HHI_beds1 = scale1(datC$HHI_beds),
  gdp1 = scale1(datC$gdp)
)

rats_fit <- stan(model_code=tobitstan, model_name="Bayesian Tobit", data=tdat1, iter=5000,warmup = 2500, chains=1, seed = 111, control = list(adapt_delta = 0.99))

rstan::summary(rats_fit)
shinystan::launch_shinystan(rats_fit)
```

```{r brms}
library(brms)
library(tidyverse)
dat = haven::read_dta("data/dat.dta")
dat$censoring = 0
dat$censoring[dat$TE == 1] = 1

dat1 = dat %>% 
  select(TE, censoring, bed, occ, alos, dnr, bnr, oir, pop, urban, HHI_beds, gdp) %>% 
  mutate_all(as.numeric)
  

fit1 = brm(bf(TE|cens(censoring) ~ bed + occ + alos + dnr + bnr + oir + pop + urban + HHI_beds + gdp), data = dat1, chains = 1)
```



























































